air_hockey:
  agent:
    rate: 100
    tcp_position: [ 0.0, 0.0, 0.515 ]
    tcp_quaternion: [ 1.0, 0.0, 0.0, 0.0 ]  # [ w, x, y, z ]
    home: [0.08, 0.0]
    defend_line: 0.2
    hit_range: [0.1, 0.9]
    universal_joint_height:  0.095 # 0.085 #
    max_hit_velocity: 1.2
    min_defend_velocity: 0.05
    min_defend_time: 0.3
    controller: joint_position_trajectory_controller
    q_ref: [1.7207, 0.6541, -1.859, -1.422, 0.1313, 1.3779, -0.0653]