air_hockey:
  agent:
    rate: 100
    tcp_position: [ 0.0, 0.0, 0.515 ]
    tcp_quaternion: [ 1.0, 0.0, 0.0, 0.0 ]  # [ w, x, y, z ]
    home: [0.58, 0.0]
    goal: [2.484, 0.0]
    defend_line: 0.2
    hit_range: [0.7, 1.3]
    max_hit_velocity: 1.5
    min_defend_velocity: 0.05
    min_defend_time: 0.3
    q_init: [1.4667675, 1.1785414, -1.502088, -0.99056375, 0.07174191, 1.7372178, 0.]