neural_planner:
  planner_path: "./scripts/manifold_planning/trained_models/hitting/best-149" # used for hitting experiments
  #planner_path: "./scripts/manifold_planning/trained_models/hitting/tricks/last_n-111" # used for trick-shots
