neural_planner:
  planner_path: "./trained_models/striker/opt_man_lp/best-149" # works well LP (used for experiments)

  #planner_path: "./trained_models/striker/opt_man_lp/general/last_n-111" # general LP works ok but sometimes goes to high (used for trick-shots)
#  planner_path: "./trained_models/striker/opt_man_lp/general/last_n-108" # general LP reliable general model, which fails to score sometimes (tested on the last day)

  #planner_path: "./trained_models/striker/opt_man_lp/general/last_n-156" # general LP porthos tighter but still problems for >=7 and short plans
#  planner_path: "./trained_models/striker/opt_man_lp/general/last_n-203" # general LP porthos tighter but still problems for >=7

  #planner_path: "./trained_models/striker/n9/last_n-122"
  #planner_path: "./trained_models/striker/n9/last_n-132"
  #planner_path: "./trained_models/striker/n12/last_n-119"
  #planner_path: "./trained_models/striker/n15/last_n-126"
  #planner_path: "./trained_models/striker/n18/last_n-105"
  #planner_path: "./trained_models/striker/n21/last_n-111"

  #planner_path: "./trained_models/striker/heights/last_n-124"
  #planner_path: "./trained_models/striker/heights/last_n-132"

  #planner_path: "./trained_models/striker/10percent/last_n-105"
  #planner_path: "./trained_models/striker/1percent/best-307"
  #planner_path: "./trained_models/striker/01percent/last_n-82"



#  ik_hitting_path: "./trained_models/ik_hitting/pos_lossabs/best-53"
  ik_hitting_path: "./trained_models/ik_hitting/pos_lossabs/best-77"
#  ik_hitting_path: "./trained_models/ik_hitting/pos_lossabs/best-138"
