//
// Created by puze on 16.02.21.
//

#ifndef AIRHOCKEY_AIR_HOCKEY_STACK_AIR_HOCKEY_BASELINE_AGENT_INCLUDE_AIR_HOCKEY_BASELINE_AGENT_UTILS_H_
#define AIRHOCKEY_AIR_HOCKEY_STACK_AIR_HOCKEY_BASELINE_AGENT_INCLUDE_AIR_HOCKEY_BASELINE_AGENT_UTILS_H_

#include <Eigen/Dense>

namespace air_hockey_baseline_agent{
	void GetNullSpace(const Eigen::MatrixXd &A, Eigen::MatrixXd &out_null_space);
}

#endif //AIRHOCKEY_AIR_HOCKEY_STACK_AIR_HOCKEY_BASELINE_AGENT_INCLUDE_AIR_HOCKEY_BASELINE_AGENT_UTILS_H_
