air_hockey:
  mallet_radius: 0.04815
  puck_radius: 0.03065
  table_length: 1.96
  table_width: 1.02
  universal_joint_height: 0.165 # Table surface height (0.1) + mallet height (0.095) - base height(0.03)
  goal_width: 0.25