iiwa_front:
  # This controller is not used
  striker_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - F_striker_joint_1
      - F_striker_joint_2
    F_striker_joint_1:
      pid: { p: 10.0, i: 0.1, d: 0.005, i_clamp_min: -10000, i_clamp_max: 10000 }
    F_striker_joint_2:
      pid: { p: 10.0, i: 0.1, d: 0.005, i_clamp_min: -10000, i_clamp_max: 10000 }

iiwa_back:
  # This controller is not used
  striker_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - B_striker_joint_1
      - B_striker_joint_2

    B_striker_joint_1:
      pid: { p: 100.0, i: 0.1, d: 0.01, i_clamp_min: -10000, i_clamp_max: 10000 }
    B_striker_joint_2:
      pid: { p: 100.0, i: 0.1, d: 0.01, i_clamp_min: -10000, i_clamp_max: 10000 }