<?xml version="1.0" encoding="utf-8"?>
<robot name="puck" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <material name="red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material>

    <xacro:arg name="parent" default="world"/>
    <xacro:property name="puck_radius" value="0.03165"/>
    <xacro:property name="puck_height" value="0.0049"/>

    <xacro:property name="restitution" value="0.8"/>
    <xacro:property name="lateral_friction" value="0.02"/>
    <xacro:property name="rolling_friction" value="0.8"/>
    <xacro:property name="spinning_friction" value="0.04"/>

    <xacro:macro name="puck" params="parent">
        <link name="${parent}"/>

        <joint name="base_joint" type="fixed">
            <origin xyz="0 0 ${puck_height/2}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="link"/>
        </joint>

        <link name="link">
            <inertial>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="2e-5"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height}"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <origin xyz="0 0 0.05" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height + 0.1}"/>
                </geometry>
            </collision>
            <contact>
                <restitution value="${restitution}"/>
                <lateral_friction value="${lateral_friction}"/>
                <rolling_friction value="0.0"/>
                <spinning_friction value="0.0"/>
            </contact>
        </link>

        <gazebo reference="link">
            <collision>
                <surface>
                    <bounce>
                        <restitution_coefficient>${restitution}</restitution_coefficient>
                        <threshold>0.0</threshold>
                    </bounce>
                    <friction>
                        <!-- For Gazebo Must contain tag ode, mu, mu2, check https://github.com/osrf/sdformat/issues/31 -->
                        <!-- https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/bullet/BulletSurfaceParams.cc -->
                        <ode>
                            <mu>${lateral_friction}</mu>
                            <mu2>${lateral_friction}</mu2>
                        </ode>
                    </friction>
                    <contact>
                        <ode>
                            <max_vel>100</max_vel>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <material>Gazebo/Red</material>
        </gazebo>

        <gazebo>
            <plugin name="puck_tf_plugin" filename="libpuck_tf_plugin.so">
            </plugin>
        </gazebo>

    </xacro:macro>

    <xacro:puck parent="$(arg parent)"/>
</robot>

