<?xml version="1.0" encoding="utf-8"?>
<robot name="puck" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="Red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material>

    <material name="Green">
        <color rgba="0.0 1.0 0.0 1"/>
    </material>

    <material name="Blue">
        <color rgba="0.0 0.0 1.0 1"/>
    </material>

    <xacro:arg name="puck_name" default="Puck"/>
    <xacro:arg name="color" default="Red"/>
    <xacro:arg name="collide_bitmask" default="0x03"/>
    <xacro:arg name="restitution" default="1.0"/>
    <xacro:arg name="lateral_friction" default="1.0"/>
    <xacro:arg name="spinning_friction" default="0.002104678089464182"/>
    <xacro:arg name="linear_vel_decay" default="0.00041985197458416224"/>
    <xacro:arg name="angular_vel_decay" default="0.0007291871439489361"/>

    <xacro:property name="puck_radius" value="0.03165"/>
    <xacro:property name="puck_height" value="0.0049"/>

    <xacro:macro name="puck" params="puck_name color collide_bitmask restitution
                                     lateral_friction spinning_friction linear_vel_decay angular_vel_decay">
        <link name="${puck_name}"/>

        <joint name="{puck_name}_joint" type="fixed">
            <origin xyz="0 0 ${puck_height/2}" rpy="0 0 0"/>
            <parent link="${puck_name}"/>
            <child link="${puck_name}_link"/>
        </joint>

        <link name="${puck_name}_link">
            <inertial>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="5e-6"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height}"/>
                </geometry>
                <material name="${color}"/>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height}"/>
                </geometry>
            </collision>
            <contact>
                <restitution value="$(arg restitution)"/>
                <lateral_friction value="${lateral_friction}"/>
                <rolling_friction value="0.0"/>
                <spinning_friction value="${spinning_friction}"/>
            </contact>
        </link>

        <gazebo reference="${puck_name}">
            <velocity_decay>
                <linear>${linear_vel_decay}</linear>
                <angular>${angular_vel_decay}</angular>
            </velocity_decay>
            <collision>
                <surface>
                    <bounce>
                        <restitution_coefficient>${restitution}</restitution_coefficient>
                        <threshold>0.0</threshold>
                    </bounce>
                    <friction>
                        <!-- For Gazebo Must contain tag ode, mu, mu2, check https://github.com/osrf/sdformat/issues/31 -->
                        <!-- https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/bullet/BulletSurfaceParams.cc -->
                        <torsional>
                            <coefficient>${spinning_friction}</coefficient>
                            <use_patch_radius>true</use_patch_radius>
                            <patch_radius>${puck_radius}</patch_radius>
                        </torsional>
                        <ode>
                            <mu>${lateral_friction}</mu>
                            <mu2>${lateral_friction}</mu2>
                        </ode>
                    </friction>
                    <contact>
                        <collide_bitmask>${collide_bitmask}</collide_bitmask>
                        <ode>
                            <kp>1e9</kp>
                            <max_vel>20</max_vel>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <material>Gazebo/Red</material>
        </gazebo>

        <gazebo>
            <updateRate>500.0</updateRate>
            <plugin name="puck_tf_plugin" filename="libpuck_tf_plugin.so">
            </plugin>
        </gazebo>

    </xacro:macro>

    <xacro:puck puck_name="$(arg puck_name)"
                collide_bitmask="$(arg collide_bitmask)"
                color="$(arg color)"
                restitution="$(arg restitution)"
                lateral_friction="$(arg lateral_friction)"
                spinning_friction="$(arg spinning_friction)"
                linear_vel_decay="$(arg linear_vel_decay)"
                angular_vel_decay="$(arg angular_vel_decay)"/>
</robot>

