<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="air_hockey">
    <material name="red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material>

    <xacro:arg name="puck_base_x" default="0.0"/>
    <xacro:arg name="puck_base_y" default="0.0"/>
    <xacro:arg name="puck_base_z" default="0.0"/>

    <xacro:property name="puck_radius" value="0.03165"/>
    <xacro:property name="puck_height" value="0.0049"/>

    <xacro:property name="restitution" value="0.8"/>
    <xacro:property name="lateral_friction" value="0.04"/>
    <xacro:property name="rolling_friction" value="0.8"/>
    <xacro:property name="spinning_friction" value="0.04"/>

    <xacro:macro name="puck">
        <link name="root">
        </link>

        <joint name="base_joint" type="fixed">
            <origin xyz="0 0 ${puck_height/2}" rpy="0 0 0"/>
            <parent link="root"/>
            <child link="base"/>
        </joint>

        <link name="base">
            <inertial>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="2e-5"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height}"/>
                </geometry>
                <material name="red"/>
                <material>Gazebo/Orange</material>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${puck_radius}" length="${puck_height}"/>
                </geometry>
                <surface>
                    <restitution_coefficient>${restitution}</restitution_coefficient>
                    <threshold>0.01</threshold>
                </surface>
                <friction>
                    <ode>
                        <!-- For Gazebo Must contain tag ode, mu, mu2, check https://github.com/osrf/sdformat/issues/31 -->
                        <!-- https://github.com/osrf/gazebo/blob/gazebo11/gazebo/physics/bullet/BulletSurfaceParams.cc -->
                        <mu>${lateral_friction}</mu>
                        <mu2>${lateral_friction}</mu2>
                    </ode>
                </friction>
            </collision>
            <contact>
                <restitution value="${restitution}"/>
                <lateral_friction value="${lateral_friction}"/>
                <rolling_friction value="0.0"/>
                <spinning_friction value="0.0"/>
            </contact>
        </link>

        <gazebo reference="base">
<!--            <mu1>${lateral_friction}</mu1>-->
<!--            <mu2>${lateral_friction}</mu2>-->
            <maxVel value="10.0"/>
            <material>Gazebo/Red</material>
        </gazebo>

    </xacro:macro>

    <xacro:puck/>
</robot>

