air_hockey:
  puck_tracker:
    max_prediction_steps:
      240
    frequency:
      120
    friction_drag:
      0.001
    friction_sliding:
      0.063
    restitution_table:
      0.8468189914210034
    restitution_mallet:
      0.8
    observation_variance_position:
      2.5e-7
    observation_variance_angular:
      2.5e-7
    dynamic_variance_position:
      1.0e-6
    dynamic_variance_velocity:
      1.0e-4
    dynamic_variance_angular_position:
      1.0e-6
    dynamic_variance_angular_velocity:
      1.0e-6