air_hockey:
  puck_tracker:
    max_prediction_steps:
      60
    frequency:
      120
    friction_drag:
      0.35
    friction_sliding:
      0.018
    restitution_table:
      0.92
    restitution_mallet:
      0.8
    rim_friction:
      0.2
    observation_variance_position:
      2.5e-7
    observation_variance_angular:
      2.5e-7
    dynamic_variance_position:
      2e-10
    dynamic_variance_velocity:
      3e-7
    dynamic_variance_angular_position:
      1.0e-6
    dynamic_variance_angular_velocity:
      1.0e-6
    reset_threshold:
      4.605170185988092   # gating value pG = 0.9 of cdf from Chi squared distribution in 2 DoF (x, y)
    turn_on_pf:
      false