#!/usr/bin/env python

import sys

from air_hockey_rqt.air_hockey_manager import AirHockeyManager
from rqt_gui.main import Main

plugin = 'air_hockey_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))